// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjZTzxa2teORfLjmRJ3l1PUpLaZUVUWao',
    appId: '1:679102322266:web:6c9941079e9755d2af6a63',
    messagingSenderId: '679102322266',
    projectId: 'whatsapp-clone-2c738',
    authDomain: 'whatsapp-clone-2c738.firebaseapp.com',
    storageBucket: 'whatsapp-clone-2c738.firebasestorage.app',
    measurementId: 'G-NM57FXFFD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8yLpCagMue572mKdUmVtZgUeVDHwUhC4',
    appId: '1:679102322266:android:921ea4daeb671492af6a63',
    messagingSenderId: '679102322266',
    projectId: 'whatsapp-clone-2c738',
    storageBucket: 'whatsapp-clone-2c738.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Ug1xzsxBZom8trE0jQzlhA74dXiCqNY',
    appId: '1:679102322266:ios:048a1e64e297eee3af6a63',
    messagingSenderId: '679102322266',
    projectId: 'whatsapp-clone-2c738',
    storageBucket: 'whatsapp-clone-2c738.firebasestorage.app',
    iosBundleId: 'com.coder.shubham',
  );
}
